import Foundation

enum CoreVerifiedFoodCatalog {
    static let entries: [VerifiedFoodEntry] = [
        VerifiedFoodEntry(
            name: "Ức gà",
            calories: 165,
            protein: 31.0,
            carbs: 0.0,
            fat: 3.6,
            unit: "100g",
            searchAliases: ["gà", "thịt gà", "chicken breast"],
            remoteSearchAliases: ["chicken breast", "chicken"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Trứng gà",
            calories: 78,
            protein: 6.3,
            carbs: 0.6,
            fat: 5.3,
            unit: "1 quả (50g)",
            servingSize: .grams(50),
            searchAliases: ["trứng", "egg", "chicken egg"],
            remoteSearchAliases: ["egg", "chicken egg"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Cơm trắng",
            calories: 130,
            protein: 2.7,
            carbs: 28.0,
            fat: 0.3,
            unit: "100g",
            searchAliases: ["cơm", "gạo trắng", "white rice"],
            remoteSearchAliases: ["white rice", "rice"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Chuối",
            calories: 89,
            protein: 1.1,
            carbs: 22.8,
            fat: 0.3,
            unit: "100g",
            searchAliases: ["banana"],
            remoteSearchAliases: ["banana"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Yến mạch",
            calories: 389,
            protein: 16.9,
            carbs: 66.3,
            fat: 6.9,
            unit: "100g",
            searchAliases: ["oats", "oatmeal"],
            remoteSearchAliases: ["oats", "oatmeal"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Sữa chua không đường",
            calories: 63,
            protein: 5.3,
            carbs: 7.0,
            fat: 1.6,
            unit: "100g",
            searchAliases: ["sữa chua", "yogurt", "plain yogurt"],
            remoteSearchAliases: ["plain yogurt", "unsweetened yogurt", "yogurt"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Thịt bò nạc",
            calories: 217,
            protein: 26.1,
            carbs: 0.0,
            fat: 11.8,
            unit: "100g",
            searchAliases: ["thịt bò", "bò", "beef", "lean beef"],
            remoteSearchAliases: ["lean beef", "beef"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Thịt lợn nạc",
            calories: 143,
            protein: 26.2,
            carbs: 0.0,
            fat: 3.5,
            unit: "100g",
            searchAliases: ["thịt lợn", "thịt heo", "heo nạc", "pork tenderloin", "lean pork"],
            remoteSearchAliases: ["pork tenderloin", "lean pork", "pork"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Ba chỉ lợn",
            calories: 518,
            protein: 9.3,
            carbs: 0.0,
            fat: 53.0,
            unit: "100g",
            searchAliases: ["ba chỉ", "ba rọi", "ba chỉ heo", "pork belly"],
            remoteSearchAliases: ["pork belly"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Đùi gà bỏ da",
            calories: 209,
            protein: 26.0,
            carbs: 0.0,
            fat: 10.9,
            unit: "100g",
            searchAliases: ["đùi gà", "thịt đùi gà", "chicken thigh"],
            remoteSearchAliases: ["chicken thigh", "skinless chicken thigh"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Cá hồi",
            calories: 206,
            protein: 22.1,
            carbs: 0.0,
            fat: 12.4,
            unit: "100g",
            searchAliases: ["salmon"],
            remoteSearchAliases: ["salmon"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Cá ngừ",
            calories: 132,
            protein: 28.0,
            carbs: 0.0,
            fat: 1.3,
            unit: "100g",
            searchAliases: ["tuna"],
            remoteSearchAliases: ["tuna"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Cá basa",
            calories: 120,
            protein: 18.0,
            carbs: 0.0,
            fat: 5.0,
            unit: "100g",
            searchAliases: ["basa", "pangasius", "cá tra"],
            remoteSearchAliases: ["pangasius", "basa fish"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Tôm luộc",
            calories: 119,
            protein: 22.8,
            carbs: 1.5,
            fat: 1.7,
            unit: "100g",
            searchAliases: ["tôm", "shrimp", "prawn"],
            remoteSearchAliases: ["cooked shrimp", "shrimp", "prawn"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Mực",
            calories: 92,
            protein: 15.6,
            carbs: 3.1,
            fat: 1.4,
            unit: "100g",
            searchAliases: ["squid", "calamari"],
            remoteSearchAliases: ["squid", "calamari"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Đậu phụ",
            calories: 76,
            protein: 8.0,
            carbs: 1.9,
            fat: 4.8,
            unit: "100g",
            searchAliases: ["đậu hũ", "tofu"],
            remoteSearchAliases: ["tofu", "firm tofu"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Sữa tươi không đường",
            calories: 61,
            protein: 3.2,
            carbs: 4.8,
            fat: 3.3,
            unit: "100ml",
            servingSize: .milliliters(100),
            searchAliases: ["sữa tươi", "milk", "unsweetened milk"],
            remoteSearchAliases: ["whole milk", "unsweetened milk", "milk"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Khoai lang",
            calories: 90,
            protein: 2.0,
            carbs: 20.7,
            fat: 0.2,
            unit: "100g",
            searchAliases: ["sweet potato", "khoai"],
            remoteSearchAliases: ["sweet potato", "baked sweet potato"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Khoai tây",
            calories: 87,
            protein: 1.9,
            carbs: 20.1,
            fat: 0.1,
            unit: "100g",
            searchAliases: ["potato"],
            remoteSearchAliases: ["potato", "boiled potato"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Bắp ngô",
            calories: 96,
            protein: 3.4,
            carbs: 21.0,
            fat: 1.5,
            unit: "100g",
            searchAliases: ["bắp", "ngô", "corn", "sweet corn"],
            remoteSearchAliases: ["sweet corn", "corn"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Bông cải xanh",
            calories: 34,
            protein: 2.8,
            carbs: 6.6,
            fat: 0.4,
            unit: "100g",
            searchAliases: ["súp lơ xanh", "broccoli"],
            remoteSearchAliases: ["broccoli"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Cà rốt",
            calories: 41,
            protein: 0.9,
            carbs: 9.6,
            fat: 0.2,
            unit: "100g",
            searchAliases: ["carrot"],
            remoteSearchAliases: ["carrot", "raw carrot"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Cải bó xôi",
            calories: 23,
            protein: 2.9,
            carbs: 3.6,
            fat: 0.4,
            unit: "100g",
            searchAliases: ["rau bina", "spinach"],
            remoteSearchAliases: ["spinach"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Dưa leo",
            calories: 15,
            protein: 0.7,
            carbs: 3.6,
            fat: 0.1,
            unit: "100g",
            searchAliases: ["dưa chuột", "cucumber"],
            remoteSearchAliases: ["cucumber"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Cà chua",
            calories: 18,
            protein: 0.9,
            carbs: 3.9,
            fat: 0.2,
            unit: "100g",
            searchAliases: ["tomato"],
            remoteSearchAliases: ["tomato"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Táo",
            calories: 52,
            protein: 0.3,
            carbs: 13.8,
            fat: 0.2,
            unit: "100g",
            searchAliases: ["apple"],
            remoteSearchAliases: ["apple"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Cam",
            calories: 47,
            protein: 0.9,
            carbs: 11.8,
            fat: 0.1,
            unit: "100g",
            searchAliases: ["orange"],
            remoteSearchAliases: ["orange"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Bơ",
            calories: 160,
            protein: 2.0,
            carbs: 8.5,
            fat: 14.7,
            unit: "100g",
            searchAliases: ["trái bơ", "avocado"],
            remoteSearchAliases: ["avocado"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Cơm gạo lứt",
            calories: 112,
            protein: 2.3,
            carbs: 23.5,
            fat: 0.8,
            unit: "100g",
            searchAliases: ["gạo lứt", "brown rice"],
            remoteSearchAliases: ["brown rice", "cooked brown rice"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Bún tươi",
            calories: 110,
            protein: 1.7,
            carbs: 25.0,
            fat: 0.2,
            unit: "100g",
            searchAliases: ["bún", "rice vermicelli"],
            remoteSearchAliases: ["rice vermicelli", "rice noodles"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
        VerifiedFoodEntry(
            name: "Sữa đậu nành không đường",
            calories: 33,
            protein: 2.9,
            carbs: 1.7,
            fat: 1.8,
            unit: "100ml",
            servingSize: .milliliters(100),
            searchAliases: ["sữa đậu nành", "soy milk", "unsweetened soy milk"],
            remoteSearchAliases: ["unsweetened soy milk", "soy milk"],
            source: .nutritionReference,
            confidence: .referenceBased
        ),
    ]
}
