import Foundation

enum VietnameseMealsCatalog {
    static let entries: [VerifiedFoodEntry] = [
        VerifiedFoodEntry(
            name: "Phở bò",
            calories: 400,
            protein: 22.0,
            carbs: 55.0,
            fat: 9.0,
            unit: "1 tô (500g)",
            servingSize: .grams(500),
            searchAliases: ["phở", "beef pho"],
            remoteSearchAliases: ["pho", "beef pho"],
            source: .vietnameseCuratedEstimate,
            confidence: .estimated
        ),
        VerifiedFoodEntry(
            name: "Bún chả",
            calories: 480,
            protein: 28.0,
            carbs: 55.0,
            fat: 15.0,
            unit: "1 phần (400g)",
            servingSize: .grams(400),
            searchAliases: ["bun cha"],
            remoteSearchAliases: ["bun cha"],
            source: .vietnameseCuratedEstimate,
            confidence: .estimated
        ),
        VerifiedFoodEntry(
            name: "Cơm tấm sườn bì",
            calories: 650,
            protein: 30.0,
            carbs: 70.0,
            fat: 25.0,
            unit: "1 đĩa (400g)",
            servingSize: .grams(400),
            searchAliases: ["cơm tấm", "sườn bì", "broken rice"],
            remoteSearchAliases: ["broken rice", "com tam"],
            source: .vietnameseCuratedEstimate,
            confidence: .estimated
        ),
        VerifiedFoodEntry(
            name: "Bánh mì thịt",
            calories: 350,
            protein: 16.0,
            carbs: 42.0,
            fat: 12.0,
            unit: "1 ổ (180g)",
            servingSize: .grams(180),
            searchAliases: ["bánh mì", "banh mi", "vietnamese sandwich"],
            remoteSearchAliases: ["banh mi", "vietnamese sandwich"],
            source: .vietnameseCuratedEstimate,
            confidence: .estimated
        ),
        VerifiedFoodEntry(
            name: "Bún bò Huế",
            calories: 430,
            protein: 24.0,
            carbs: 58.0,
            fat: 11.0,
            unit: "1 tô (500g)",
            servingSize: .grams(500),
            searchAliases: ["bún bò", "bun bo hue"],
            remoteSearchAliases: ["bun bo hue", "spicy beef noodle soup"],
            source: .vietnameseCuratedEstimate,
            confidence: .estimated
        ),
        VerifiedFoodEntry(
            name: "Phở gà",
            calories: 350,
            protein: 20.0,
            carbs: 52.0,
            fat: 7.0,
            unit: "1 tô (500g)",
            servingSize: .grams(500),
            searchAliases: ["phở", "chicken pho"],
            remoteSearchAliases: ["chicken pho", "pho ga"],
            source: .vietnameseCuratedEstimate,
            confidence: .estimated
        ),
        VerifiedFoodEntry(
            name: "Bún riêu cua",
            calories: 380,
            protein: 18.0,
            carbs: 52.0,
            fat: 10.0,
            unit: "1 tô (500g)",
            servingSize: .grams(500),
            searchAliases: ["bún riêu", "bun rieu"],
            remoteSearchAliases: ["bun rieu", "crab noodle soup"],
            source: .vietnameseCuratedEstimate,
            confidence: .estimated
        ),
        VerifiedFoodEntry(
            name: "Cơm gà xối mỡ",
            calories: 550,
            protein: 32.0,
            carbs: 55.0,
            fat: 20.0,
            unit: "1 đĩa (350g)",
            servingSize: .grams(350),
            searchAliases: ["cơm gà", "fried chicken rice"],
            remoteSearchAliases: ["chicken rice", "fried chicken rice"],
            source: .vietnameseCuratedEstimate,
            confidence: .estimated
        ),
        VerifiedFoodEntry(
            name: "Hủ tiếu Nam Vang",
            calories: 420,
            protein: 22.0,
            carbs: 55.0,
            fat: 11.0,
            unit: "1 tô (500g)",
            servingSize: .grams(500),
            searchAliases: ["hủ tiếu", "hu tieu"],
            remoteSearchAliases: ["hu tieu", "vietnamese pork noodle soup"],
            source: .vietnameseCuratedEstimate,
            confidence: .estimated
        ),
        VerifiedFoodEntry(
            name: "Mì Quảng",
            calories: 460,
            protein: 24.0,
            carbs: 60.0,
            fat: 12.0,
            unit: "1 tô (400g)",
            servingSize: .grams(400),
            searchAliases: ["mi quang"],
            remoteSearchAliases: ["mi quang", "vietnamese turmeric noodle"],
            source: .vietnameseCuratedEstimate,
            confidence: .estimated
        ),
        VerifiedFoodEntry(
            name: "Bánh mì trứng",
            calories: 300,
            protein: 12.0,
            carbs: 40.0,
            fat: 10.0,
            unit: "1 ổ (180g)",
            servingSize: .grams(180),
            searchAliases: ["bánh mì", "bánh mì ốp la", "egg banh mi"],
            remoteSearchAliases: ["egg banh mi", "egg sandwich"],
            source: .vietnameseCuratedEstimate,
            confidence: .estimated
        ),
        VerifiedFoodEntry(
            name: "Cháo gà",
            calories: 150,
            protein: 12.0,
            carbs: 20.0,
            fat: 3.0,
            unit: "1 tô (300g)",
            servingSize: .grams(300),
            searchAliases: ["cháo", "chicken porridge"],
            remoteSearchAliases: ["chicken porridge", "congee"],
            source: .vietnameseCuratedEstimate,
            confidence: .estimated
        ),
        VerifiedFoodEntry(
            name: "Gỏi cuốn tôm thịt",
            calories: 120,
            protein: 8.0,
            carbs: 16.0,
            fat: 2.5,
            unit: "2 cuốn (120g)",
            servingSize: .grams(120),
            searchAliases: ["gỏi cuốn", "spring roll"],
            remoteSearchAliases: ["vietnamese spring roll", "fresh spring roll"],
            source: .vietnameseCuratedEstimate,
            confidence: .estimated
        ),
        VerifiedFoodEntry(
            name: "Cà phê sữa đá",
            calories: 120,
            protein: 2.0,
            carbs: 18.0,
            fat: 4.0,
            unit: "1 ly (250ml)",
            servingSize: .milliliters(250),
            searchAliases: ["cà phê sữa", "coffee milk"],
            remoteSearchAliases: ["vietnamese iced coffee", "coffee with condensed milk"],
            source: .vietnameseCuratedEstimate,
            confidence: .estimated
        ),
        VerifiedFoodEntry(
            name: "Chả giò",
            calories: 200,
            protein: 8.0,
            carbs: 18.0,
            fat: 11.0,
            unit: "3 cuốn (100g)",
            servingSize: .grams(100),
            searchAliases: ["nem rán", "fried spring roll"],
            remoteSearchAliases: ["fried spring roll", "vietnamese egg roll"],
            source: .vietnameseCuratedEstimate,
            confidence: .estimated
        ),
        VerifiedFoodEntry(
            name: "Bún thịt nướng",
            calories: 550,
            protein: 28.0,
            carbs: 65.0,
            fat: 18.0,
            unit: "1 tô (450g)",
            servingSize: .grams(450),
            searchAliases: ["bún thịt nướng", "bun thit nuong", "grilled pork vermicelli"],
            remoteSearchAliases: ["bun thit nuong", "grilled pork vermicelli"],
            source: .vietnameseCuratedEstimate,
            confidence: .estimated
        ),
        VerifiedFoodEntry(
            name: "Bánh cuốn",
            calories: 350,
            protein: 12.0,
            carbs: 55.0,
            fat: 8.0,
            unit: "1 phần (300g)",
            servingSize: .grams(300),
            searchAliases: ["banh cuon", "steamed rice roll"],
            remoteSearchAliases: ["banh cuon", "vietnamese steamed rice roll"],
            source: .vietnameseCuratedEstimate,
            confidence: .estimated
        ),
        VerifiedFoodEntry(
            name: "Miến gà",
            calories: 360,
            protein: 24.0,
            carbs: 50.0,
            fat: 7.0,
            unit: "1 tô (450g)",
            servingSize: .grams(450),
            searchAliases: ["mien ga", "chicken glass noodle soup"],
            remoteSearchAliases: ["chicken glass noodle soup", "mien ga"],
            source: .vietnameseCuratedEstimate,
            confidence: .estimated
        ),
        VerifiedFoodEntry(
            name: "Bún cá",
            calories: 390,
            protein: 22.0,
            carbs: 55.0,
            fat: 8.0,
            unit: "1 tô (500g)",
            servingSize: .grams(500),
            searchAliases: ["bun ca", "fish noodle soup"],
            remoteSearchAliases: ["fish noodle soup", "bun ca"],
            source: .vietnameseCuratedEstimate,
            confidence: .estimated
        ),
        VerifiedFoodEntry(
            name: "Xôi gà",
            calories: 550,
            protein: 25.0,
            carbs: 70.0,
            fat: 18.0,
            unit: "1 phần (350g)",
            servingSize: .grams(350),
            searchAliases: ["xôi", "xoi ga", "chicken sticky rice"],
            remoteSearchAliases: ["chicken sticky rice", "xoi ga"],
            source: .vietnameseCuratedEstimate,
            confidence: .estimated
        ),
        VerifiedFoodEntry(
            name: "Bánh xèo",
            calories: 450,
            protein: 15.0,
            carbs: 50.0,
            fat: 20.0,
            unit: "1 cái (250g)",
            servingSize: .grams(250),
            searchAliases: ["banh xeo", "vietnamese pancake"],
            remoteSearchAliases: ["banh xeo", "vietnamese pancake"],
            source: .vietnameseCuratedEstimate,
            confidence: .estimated
        ),
        VerifiedFoodEntry(
            name: "Bò lúc lắc",
            calories: 450,
            protein: 30.0,
            carbs: 20.0,
            fat: 25.0,
            unit: "1 phần (300g)",
            servingSize: .grams(300),
            searchAliases: ["bo luc lac", "shaking beef"],
            remoteSearchAliases: ["shaking beef", "bo luc lac"],
            source: .vietnameseCuratedEstimate,
            confidence: .estimated
        ),
        VerifiedFoodEntry(
            name: "Canh chua cá",
            calories: 180,
            protein: 18.0,
            carbs: 12.0,
            fat: 6.0,
            unit: "1 tô (350g)",
            servingSize: .grams(350),
            searchAliases: ["canh chua", "vietnamese sour fish soup"],
            remoteSearchAliases: ["vietnamese sour fish soup", "canh chua"],
            source: .vietnameseCuratedEstimate,
            confidence: .estimated
        ),
        VerifiedFoodEntry(
            name: "Bún đậu mắm tôm",
            calories: 700,
            protein: 30.0,
            carbs: 65.0,
            fat: 35.0,
            unit: "1 phần (500g)",
            servingSize: .grams(500),
            searchAliases: ["bún đậu", "bun dau mam tom"],
            remoteSearchAliases: ["bun dau mam tom", "vietnamese tofu vermicelli"],
            source: .vietnameseCuratedEstimate,
            confidence: .estimated
        ),
        VerifiedFoodEntry(
            name: "Cơm rang dương châu",
            calories: 650,
            protein: 20.0,
            carbs: 85.0,
            fat: 20.0,
            unit: "1 đĩa (400g)",
            servingSize: .grams(400),
            searchAliases: ["cơm rang", "cơm chiên", "fried rice"],
            remoteSearchAliases: ["fried rice", "vietnamese fried rice"],
            source: .vietnameseCuratedEstimate,
            confidence: .estimated
        )
    ]
}
